blog/urls.py
from django.urls import path

from .views import (
    index,
    search,
    post_list,
    post_detail,
    post_create,
    post_update,
    post_delete,
    email_list_signup,
    IndexView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)

app_name = "blog"

urlpatterns = [
    # path('', index),
    path('', IndexView.as_view(), name='home'),
    # path('blog/', post_list, name='post-list'),
    path('post', PostListView.as_view(), name='post-list'),
    path('search', search, name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    # path('create/', post_create, name='post-create'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    # path('post/<id>/', post_detail, name='post-detail'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/<id>/update/', post_update, name='post-update'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<id>/delete/', post_delete, name='post-delete'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

courses/urls.py
from django.urls import path

from .views import TechnologyListView, TechnologyDetailView, CourseListView, CourseDetailView, LessonDetailView

app_name = 'courses'

urlpatterns = [
    path('', TechnologyListView.as_view(), name='techs'),
    path('tech/<slug>', TechnologyDetailView.as_view(), name='tech-detail'),
    path('all/', CourseListView.as_view(), name='index'),
    path('course/<slug>', CourseDetailView.as_view(), name='detail'),
    path('course/<course_slug>/lesson/<lesson_slug>', LessonDetailView.as_view(), name='lesson-detail')
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Stekos DEV Admin"
admin.site.site_title = "Stekos DEV Admin"
admin.site.index_title = "Stekos DEV Administration"

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('courses/', include('courses.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from ckeditor.fields import RichTextField


class Technology(models.Model):
    """ Save technologies available on the site """

    title = models.CharField(verbose_name=_('title of the tech'), max_length=120)
    slug = models.SlugField(verbose_name=_('tech slug'))
    image = models.ImageField(verbose_name=_('tech image'), default='default.png')
    description = RichTextField(verbose_name=_('description'))

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:tech-detail', kwargs={'slug': self.slug})

    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    @property
    def courses(self):
        return self.course_set.all().order_by('position')

    class Meta:
        verbose_name = _('Technology')
        verbose_name_plural = _('Technologies')


class Course(models.Model):
    """ Save courses on technologies available on the site """

    technology = models.ForeignKey(Technology, on_delete=models.CASCADE, verbose_name=_('belongs to'))
    position = models.IntegerField(verbose_name=_('course number'))
    title = models.CharField(verbose_name=_('title of the course'), max_length=120)
    slug = models.SlugField(verbose_name=_('course slug'))
    image = models.ImageField(verbose_name=_('course image'), default='default.png')
    # image = RichTextUploadingField(verbose_name=_('course image'), default='default.png')
    description = models.TextField(verbose_name=_('description'))
    is_free = models.BooleanField(verbose_name=_('course is free ?'), default=True)
    price = models.IntegerField(verbose_name=_('price of the course'), null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    @property
    def sections(self):
        return self.section_set.all().order_by('position')

    class Meta:
        verbose_name = _('Course')
        verbose_name_plural = _('Courses')


class Section(models.Model):
    """ Save course section """

    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True, verbose_name=_('section belongs to'))
    position = models.IntegerField(verbose_name=_('section number'))
    title = models.CharField(verbose_name=_('title of the section'), max_length=100, null=True)

    def __str__(self):
        return '%s - Section %s' % (self.course, self.position)

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')

    class Meta:
        verbose_name = _('Section')
        verbose_name_plural = _('Sections')


class Lesson(models.Model):
    """ Save lessons for available technologies courses on the site """

    slug = models.SlugField(verbose_name=_('lesson slug'))
    title = models.CharField(verbose_name=_('lesson title'), max_length=120)
    # course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True,
                                verbose_name=_('lesson belongs to'))
    position = models.IntegerField(verbose_name=_('course position in the section'))
    content = RichTextField(verbose_name=_('Content of the lesson'), null=True)
    video_url = models.CharField(max_length=200, verbose_name=_('link to the video of the course'))
    thumbnail = models.ImageField(verbose_name=_('thumbnail of the course video'))

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lesson-detail', kwargs={
            'course_slug': self.section.course.slug,
            'lesson_slug': self.slug
        })

    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View

from .models import Course, Lesson, Technology


class TechnologyListView(ListView):
    model = Technology


class TechnologyDetailView(DetailView):
    model = Technology


class CourseListView(ListView):
    model = Course


class CourseDetailView(DetailView):
    model = Course


class LessonDetailView(LoginRequiredMixin, View):
    def get(self, request, course_slug, lesson_slug, *args, **kwargs):
        course = get_object_or_404(Course, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug)
        # user_membership = get_object_or_404(UserMembership, user=request.user)
        # user_membership_type = user_membership.membership.membership_type
        # course_allowed_mem_types = course.allowed_memberships.all()
        context = {
            'course': course,
            'lesson': lesson
        }
        # if course_allowed_mem_types.filter(membership_type=user_membership_type).exists():
        #     context = {'object': lesson}
        return render(request, "courses/lesson-detail.html", context)

courses/templates/courses/layouts/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>{% block title %} Bienvenue sur kumasteph.dev {% endblock %}</title>

        <!-- links -->
        <link rel="stylesheet" href="{% static "courses/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "courses/css/simple-sidebar.css" %}">
        <link rel="stylesheet" href="{% static "courses/css/fontawesome.min.css" %}">
    </head>

    <body>
        <div id="wrapper" class="d-flex">

            <!-- Sidebar -->
            <div class="bg-transparent border-right" id="sidebar-wrapper">
                <div class="sidebar-heading">Stekos<sup>DEV</sup> </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url "courses:index" %}" class="list-group-item-action bg-transparent"><i class="fas fa-home"></i> Tableau de board</a><br><br>
                        <a href="{% url "courses:techs" %}" class="list-group-item-action bg-transparent"><i class="fa fa-book"></i> Feuille de route</a><br><br>
                        <a href="{% url "courses:index" %}" class="list-group-item-action bg-transparent"><i class="fa fa-book-open"></i> Cours</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'blog:home' %}" class="list-group-item-action bg-transparent"><i class="fa fa-blog"></i> Blog</a><br><br>
                        <a href="#" class="list-group-item-action bg-transparent"><i class="fa fa-forumbee"></i> Forum</a><br><br>
                    </li>
                    <li class="list-group-item ">
                        <a href="#" class="list-group-item-action bg-transparent"><i class="fa fa-info"></i> A Propos</a><br><br>
                        <a href="#" class="list-group-item-action bg-transparent"><i class="fab fa-accusoft"></i> Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /#sidebar-wrapper -->

            <!-- Page Content -->
            <div id="page-content-wrapper" class="bg-light">

                <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
                    <button class="btn btn-primary" id="menu-toggle"><i class="fa fa-bread-slice"></i> Menu</button>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div style="margin-left: 5vh;">
                        <form class="form-inline">
                            <input class="form-control mr-sm-2" type="search" placeholder="Chercher" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Chercher</button>
                        </form>
                    </div>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Utilisateur
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url "courses:index" %}">Accueil</a>
                                    <a class="dropdown-item" href="#">Profile</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Déconnexion</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>

                <div class="container-fluid" style="margin-top: 3vh">
                    {% block content %}
                        <h5 class="mt-4">Bienvenue Sur Votre Tableau</h5>
                        <div class="row">
                            <div class="col-sm-12 col-md-7">
                                <div class="card">
                                    <div class="card-body">
                                        <h6>Expériences accumulée aucours de la semaine passée</h6>
                                        <pre>







                                        </pre>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-5">
                                <div class="card">
                                    <div class="card-body">
                                        <h6>Votre travail quoditien <span class="badge badge-success">0 pas de mise à jour</span></h6>
                                        <br><p>Vous n'avez pas de travail à faire cette semaine</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row" style="margin-top: 5vh">
                        <div class="col-sm-12 col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <h6>Activités récentes</h6>
                                    <p class="text-muted">Pas d'activités récentes. Commencer un cours pour le voir ici.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <h6>Continuer là où vous vous êtes arrêté</h6>
                                    <p class="text-muted">Commencer un cours pour voir les lectures compléter</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <h6>Ma progression</h6>
                                </div>
                                <div class="card-header">
                                    <ul class="nav nav-tabs card-header-tabs">
                                        <li class="nav-item">
                                            <a href="#" class="nav-link active">Feuille de route</a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="#" class="nav-link">Cours</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">Special title treatment</h5>
                                    <p class="card-text text-muted">Vous n'avez pas encore commencer le voyage</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endblock %}
                </div>
            </div>
            <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "courses/js/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "courses/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "courses/js/fontawesome.min.js" %}"></script>

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
        $('.collapse').collapse()
    </script>

    </body>
</html>